import Link from "next/link";

const modules = [
  ["Talep ve görev orkestrasyonu", "Çağrı, talep, görev, sorumlu birim ve SLA kaydını aynı operasyon zincirinde birleştirir."],
  ["Kapasite ve transfer görünümü", "Yatak, kaynak, rezervasyon, blokaj ve transfer seçeneklerini karar desteği için görünür kılar."],
  ["Vardiya ve insan onayı", "Görev sahipliğini, devirleri ve kritik adımlardaki yetkili onayını izlenebilir tutar."],
  ["Denetim ve raporlama", "İşlem geçmişi, zamanlanmış raporlar ve operasyon kanıtlarını tek merkezde toplar."],
];

export default function Home() {
  return <main className="marketing-shell">
    <Header />
    <section className="marketing-hero">
      <div className="hero-message"><span className="kicker">HASTANE OPERASYON KONTROL KULESİ</span><h1>Doğru talebi,<br/><em>doğru kapasite ve ekiple</em> buluşturun.</h1><p>Klinorbis; kapasite, transfer, çağrı, talep, vardiya ve onay akışlarını klinik karar vermeden tek operasyon görünümünde birleştiren çalışan ürün prototipidir.</p><div className="hero-buttons"><Link href="/demo" className="hero-primary">Operasyon demosunu incele <span>→</span></Link><a href="#pilot" className="hero-secondary">Pilot modelini gör</a></div><div className="hero-proof"><span><i/>Sentetik demo verisi</span><span><i/>İnsan onayı</span><span><i/>Denetlenebilir akış</span></div></div>
      <ProductPreview />
    </section>
    <section className="executive-strip"><article><b>Tek operasyon görünümü</b><span>Dağınık kuyruklar yerine ortak durum resmi</span></article><article><b>Karar desteği, klinik karar değil</b><span>Tanı veya tedavi kararı üretmez</span></article><article><b>Sınırları görünür otomasyon</b><span>Kritik adımlarda insan onayı korunur</span></article></section>
    <section className="marketing-section" id="platform"><Intro kicker="ÜRÜN KAPSAMI" title="Bir hastane operasyonunun kritik bağlantılarını aynı ekranda izleyin." text="Her modül; talebin kaynağı, sorumlusu, kapasite etkisi ve sonuç kaydıyla ilişkilidir."/><div className="capability-grid">{modules.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="workflow-section" id="akis"><div><span className="kicker">OPERASYON ZİNCİRİ</span><h2>Talep kaybolmadan, karar sahipsiz kalmadan.</h2><p>Gelen talep birim ve kaynak durumuyla eşleşir; otomasyonun sınırı ve onay sahibi açıkça görünür.</p></div><ol>{[["Talep veya çağrı alınır","Kaynak, öncelik ve kimliksiz referans kaydedilir."],["Birim ve kapasite değerlendirilir","Uygunluk, rezervasyon, doluluk ve alternatifler görünür."],["Otomatik ön karar, kritik adımda insan onayı","Kapasite ön kabulü, alternatif yönlendirme veya gerekçeli ret kayda geçer; acil sinyal ve klinik devirde yetkili onayı beklenir."],["Sonuç ve devir izlenir","Görev, vardiya, rapor ve denetim zinciri kapanır."]].map(([a,b],i)=><li key={a}><b>0{i+1}</b><span><strong>{a}</strong><small>{b}</small></span></li>)}</ol></section>
    <section className="trust-section" id="guven"><div className="trust-card"><span>ÜRÜN SINIRI</span><h2>Operasyon yönetir; klinik karar vermez.</h2><p>Demo kimliksiz ve sentetik veriyle çalışır. Klinorbis tanı, tedavi, klinik uygunluk veya acil tıbbi karar üretmez. Gerçek hasta kullanımı için kurumun entegrasyon, yetki, veri koruma, siber güvenlik ve kabul süreçleri ayrıca tamamlanmalıdır.</p></div><div className="trust-list">{[["Mahremiyet","Asgari veri ve kapsamlı erişim"],["İnsan denetimi","Kritik kararda yetkili onayı"],["İzlenebilirlik","Görev, karar ve değişiklik geçmişi"],["Dürüst kapsam","Pilot kanıtı üretim iddiası değildir"]].map(([a,b])=><article key={a}><b>{a}</b><span>{b}</span></article>)}</div></section>
    <section className="pilot-section" id="pilot"><div><span className="kicker">KONTROLLÜ PİLOT</span><h2>Önce tek akışı ölçün, sonra ölçekleyin.</h2><p>Bir kurum, bir operasyon senaryosu ve açık kabul ölçütleriyle 6–12 haftalık pilot. Veri sorumluluğu, destek ve başarı hedefleri başlamadan önce yazılı hâle getirilir.</p></div><div className="pilot-steps"><span><b>01</b>Keşif ve risk sınırı</span><span><b>02</b>Sandbox entegrasyonu</span><span><b>03</b>Kontrollü senaryo</span><span><b>04</b>Kabul ve ölçek kararı</span></div><Link href="/demo" className="hero-primary">Canlı demoyu aç <span>→</span></Link></section>
    <Footer />
  </main>;
}

function Header(){return <header className="marketing-header"><Link href="/" className="marketing-brand"><span>K</span><b>KLINORBIS<small>HOSPITAL OPERATIONS</small></b></Link><nav><a href="#platform">Platform</a><a href="#akis">İş akışı</a><a href="#guven">Güven</a><a href="#pilot">Pilot</a></nav><div className="marketing-actions"><Link href="/en" className="language-button">EN</Link><Link href="/demo" className="demo-button">Canlı demo</Link></div></header>}
function Intro({kicker,title,text}:{kicker:string,title:string,text:string}){return <div className="section-intro"><span className="kicker">{kicker}</span><h2>{title}</h2><p>{text}</p></div>}
function ProductPreview(){return <div className="command-preview"><div className="preview-head"><span>OPERATIONS / LIVE VIEW</span><b>DEMO</b></div><div className="preview-metrics"><article><small>Açık talepler</small><strong>28</strong><em>4 yüksek öncelik</em></article><article><small>Kapasite</small><strong>109</strong><em>Uygun kaynak</em></article><article><small>Aktif görev</small><strong>34</strong><em>6 birim</em></article></div><div className="preview-body"><div className="preview-flow"><span>01 · Talep alındı</span><span>02 · Birim doğrulandı</span><span>03 · Kapasite kontrolü</span><span>04 · İnsan onayı</span></div><div className="preview-ring"><b>94%</b><small>SLA içinde</small></div></div><div className="preview-foot"><span>Kimliksiz pilot senaryosu</span><span>Son kontrol: başarılı</span></div></div>}
function Footer(){return <footer className="marketing-footer"><div><b>KLINORBIS</b><span>Hastane operasyonlarında görünürlük, sorumluluk ve kontrollü otomasyon.</span></div><div><Link href="/en">English</Link><Link href="/demo">Demo</Link></div><small>© 2026 Ekrem Alan · Çalışan ürün prototipi · Gerçek hasta verisi için tasarlanmamıştır.</small></footer>}
