import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KLINORBIS | Hospital Operations Control Tower",
  description: "Working hospital-operations prototype for capacity, transfer, call, request, shift and approval workflows with human oversight. Synthetic demo data only.",
};

const modules=[["Demand orchestration","Connect calls, requests, tasks, accountable units and SLA records."],["Capacity and transfer view","Show resources, reservations, blocks and routing alternatives."],["Shift ownership","Keep handovers and accountable human approval traceable."],["Audit and reporting","Bring operational history and evidence into one control view."]];

export default function EnglishHome(){return <main className="marketing-shell" lang="en">
  <header className="marketing-header"><Link href="/en" className="marketing-brand"><span>K</span><b>KLINORBIS<small>HOSPITAL OPERATIONS</small></b></Link><nav><a href="#platform">Platform</a><a href="#workflow">Workflow</a><a href="#trust">Trust</a><a href="#pilot">Pilot</a></nav><div className="marketing-actions"><Link href="/" className="language-button">TR</Link><Link href="/demo" className="demo-button" hrefLang="tr">Live demo (Turkish UI)</Link></div></header>
  <section className="marketing-hero"><div className="hero-message"><span className="kicker">HOSPITAL OPERATIONS CONTROL TOWER</span><h1>Connect demand<br/><em>with capacity and accountable teams.</em></h1><p>Klinorbis is a working product prototype that brings capacity, transfer, call, request, shift and approval workflows into one operational view—without making clinical decisions.</p><div className="hero-buttons"><Link href="/demo" className="hero-primary" hrefLang="tr">Explore the operations demo (Turkish UI) <span>→</span></Link><a href="#pilot" className="hero-secondary">Review the pilot model</a></div><div className="hero-proof"><span><i/>Synthetic demo data</span><span><i/>Human approval</span><span><i/>Auditable workflow</span></div></div><Preview/></section>
  <section className="executive-strip"><article><b>One operational picture</b><span>Shared visibility instead of fragmented queues</span></article><article><b>Decision support—not clinical judgement</b><span>No diagnosis or treatment decision</span></article><article><b>Bounded automation</b><span>Human approval remains explicit</span></article></section>
  <section className="marketing-section" id="platform"><div className="section-intro"><span className="kicker">PRODUCT SCOPE</span><h2>See the critical connections of hospital operations in one place.</h2><p>Each module links the source, accountable owner, capacity impact and outcome of a request.</p></div><div className="capability-grid">{modules.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
  <section className="workflow-section" id="workflow"><div><span className="kicker">OPERATIONAL CHAIN</span><h2>Requests stay visible. Decisions stay accountable.</h2><p>Operational demand is aligned with unit and resource status while the automation boundary remains explicit.</p></div><ol>{[["Receive demand","Record source, priority and an identity-free reference."],["Evaluate capacity","Show availability, occupancy and alternatives."],["Automatic pre-decision, human approval","Capacity pre-acceptance, alternative routing or reasoned rejection is recorded; urgent signals and clinical handoffs wait for accountable approval."],["Close evidence","Track task, shift, report and audit history."]].map(([a,b],i)=><li key={a}><b>0{i+1}</b><span><strong>{a}</strong><small>{b}</small></span></li>)}</ol></section>
  <section className="trust-section" id="trust"><div className="trust-card"><span>PRODUCT BOUNDARY</span><h2>Operational coordination—not clinical decision-making.</h2><p>The demo uses synthetic, identity-free data. Klinorbis does not provide diagnosis, treatment, clinical suitability or emergency medical decisions. Real-patient use requires institution-specific identity, privacy, cybersecurity, integration and acceptance work.</p></div><div className="trust-list">{[["Privacy","Minimum necessary data and scoped access"],["Human oversight","Accountable approval for critical actions"],["Traceability","Task, decision and change history"],["Honest status","Pilot evidence is not a production claim"]].map(([a,b])=><article key={a}><b>{a}</b><span>{b}</span></article>)}</div></section>
  <section className="pilot-section" id="pilot"><div><span className="kicker">CONTROLLED PILOT</span><h2>Measure one workflow before scaling.</h2><p>A 6–12 week pilot for one institution and one operational scenario, with written data boundaries, success measures, support scope and exit criteria.</p></div><div className="pilot-steps"><span><b>01</b>Discovery and risk boundary</span><span><b>02</b>Sandbox integration</span><span><b>03</b>Controlled scenario</span><span><b>04</b>Acceptance decision</span></div><Link href="/demo" className="hero-primary" hrefLang="tr">Open live demo (Turkish UI) <span>→</span></Link></section>
  <footer className="marketing-footer"><div><b>KLINORBIS</b><span>Visibility, accountability and bounded automation for hospital operations.</span></div><div><Link href="/">Türkçe</Link><Link href="/demo">Demo</Link></div><small>© 2026 Ekrem Alan · Working product prototype · Not intended for real-patient data.</small></footer>
</main>}

function Preview(){return <div className="command-preview"><div className="preview-head"><span>OPERATIONS / LIVE VIEW</span><b>DEMO</b></div><div className="preview-metrics"><article><small>Open requests</small><strong>28</strong><em>4 high priority</em></article><article><small>Capacity</small><strong>109</strong><em>Available resources</em></article><article><small>Active tasks</small><strong>34</strong><em>6 units</em></article></div><div className="preview-body"><div className="preview-flow"><span>01 · Request received</span><span>02 · Unit verified</span><span>03 · Capacity checked</span><span>04 · Human approval</span></div><div className="preview-ring"><b>94%</b><small>Within SLA</small></div></div><div className="preview-foot"><span>Identity-free pilot</span><span>Last check: healthy</span></div></div>}
